### ISSUE TITLE
Personal threads

### ISSUE THREAD

**Issue by Ashoat** [Ashoat/squadcal#114]
Personal threads a new kind of thread with the following characteristics:

1. Personal threads have precisely two members
2. For a given pair of members, there is only one personal thread
3. Personal threads have some restrictions about what can be changed:
    - Impossible to leave a personal thread
    - Impossible to remove somebody from a personal thread
    - Impossible to add somebody to a personal thread, or create one with more than one other user
    - Impossible to set `parentThreadID` when creating or editing a personal thread
    - Impossible to change a thread's type to or from `threadTypes.PERSONAL`
4. All "fake threads" described in #12 are a specific kind of personal thread
    - The personal thread is only instantiated on the server once a message is sent to a "fake thread", or a friend request is sent from one user to the other
    - A user blocking another user does not create a personal thread
5. When actions that affect somebody's relationship with somebody else occur, they are recorded by robotext messages in the personal thread. Only sending or accepting a friend request should be recorded.
    - Most messages can be seen by both users, but when user A blocks user B this can only be seen by user A
    - However, if user B visits the thread when user A has blocked them, even though they don't see a message recording this action, they will be able to tell that they are blocked because they won't be able to message the other user
6. As discussed in #12, in any thread with just two members where at least one of them has blocked the other, no text messages can be sent
    - We can implement this by setting permissions in `threadInfoFromRawThreadInfo`
    - This applies to personal threads, but is also a general rule that applies to non-personal threads as well
7. The stuff in #12 where I talk about having UI elements in the chat view for handling friend requests should only apply to personal threads, and not to other two-personal threads
8. Personal threads should have a distinct `ThreadIcon`
9. When we launch the personal threads feature, we should have a migration script that:
    - For each pair of users, if it can find any top-level (no parent) threads that contain just the two of them, it will set the oldest matching thread to be the personal thread
    - For each pair of users that are friends, if there is no top-level thread containing just the two of them, the script will create such a thread

**Comment by Ashoat** [comment]
We'll need to rename `threadIsPersonalChat` when we start working on this feature. (That function right now just detects if it is a single-person thread.)

**Comment by palys-swm** [comment]
https://phabricator.ashoat.com/D328#inline-1359

> I'm realizing we have a similar condition here. I don't think we should handle it in the same way, since it shouldn't be possible to change type to or from threadTypes.PERSONAL, and it shouldn't be possible to set parentThreadID for a threadTypes.PERSONAL.

> I think we need some more validation:

> It shouldn't be possible to set parentThreadID for threadTypes.PERSONAL in createThread
It shouldn't be possible to set parentThreadID for threadTypes.PERSONAL in updateThread
It shouldn't be possible to change type to threadTypes.PERSONAL in updateThread
It shouldn't be possible to change type from threadTypes.PERSONAL in updateThread

**Comment by Ashoat** [comment]
Two more small things I realized we should do:
1. For the two-person threads we programmatically create on the server, we should switch the code to make sure these are `PERSONAL` threads going forward. Two places I know of:
    - [`createSquadbotThread`](https://github.com/Ashoat/squadcal/blob/master/server/src/bots/squadbot.js#L14)
    - [`createAccount`](https://github.com/Ashoat/squadcal/blob/master/server/src/creators/account-creator.js#L125), specifically the thread that gets created with me (but not the private single-person one)
2. I'd like to avoid converting squadbot's `staffThreadID` to `PERSONAL`. I commented this on [D417](https://phabricator.ashoat.com/D417). The ID of the thread is stored in `lib/facts/bots.json`

Besides that, we have @palys-swm's list from before his vacation:
> 1. Sending a message in a pending thread results in anonymous user name. I debugged it a bit, and it looks like new relationship row is created correctly but is not visible on the frontend
> 2. Migration script has to be updated
> 3. One corner case bug: when a user opens a pending thread and blocks the user, it's still possible to send a message. It fails on the backend, but we should not allow even typing it
> 4. It's possible to left a personal thread. We should block that and it requires introducing a new permission

@KatPo is almost done with 4, and is working on 3. @palys-swm already has a diff out for 2.

We also have some follow-ups from [D373](https://phabricator.ashoat.com/D373):

1. Exclude viewer from `usersSearchResults` in `ChatThreadList.listDataSelector`
2. Order the search results in `ChatThreadList`: non-pending `PERSONAL`, then the rest, then pending threads

And finally, there's the "master list" at the top of this issue. I read through that and I think most of it is handled, but would be great if @palys-swm can take a look too. One thing I thought of is that it is still possible for a user to create a two-person non-`PERSONAL` thread through `ComposeThread`, which might be a bit confusing. But I think we can scope this work under #118.

**Comment by Ashoat** [comment]
Here is a new list of what's left:

1. "Sending a message in a pending thread results in anonymous user name. I debugged it a bit, and it looks like new relationship row is created correctly but is not visible on the frontend" (reported by @palys-swm)
2. Migration script has to be updated (@palys-swm working on it)
    - Avoid converting `staffThreadID` to `PERSONAL`
3. One corner case bug: when a user opens a pending thread and blocks the user, it's still possible to send a message. It fails on the backend, but we should not allow even typing it (@KatPo working on it)
4. Use `PERSONAL` threads in `createSquadbotThread` and `createAccount` (very easy)
5. Buttons in `ThreadSettings`
