### ISSUE TITLE
Prevent blocked users from messaging each other

### ISSUE THREAD

**Issue by Ashoat** [Ashoat/squadcal#116]
1. ~~If either user A has blocked user B or vice versa, it should not be possible for either of them to create a new thread with the other, unless that thread is a subthread of a thread that both user A and user B are in (done)~~
2. ~~Same as 1, but for adding users to a thread (done)~~
3. We should make sure that the client restricts permissions for existing threads once a user blocks another
    1. Condition 1: This does not apply to threads that have an admin
        - Let's introduce a new function called `roleIsAdminRole` that tells us whether a role is an admin role
            - It should support `?RoleInfo` as input
            - We can base it off the condition in `memberIsAdmin`
            - Let's `git grep "'Admins'"` to find all places where we check whether a role is an admin role, and replace it with our new `roleIsAdminRole` function
        - Let's introduce a new function called `threadHasAdminRole` which will tell us if a thread has an admin role
            - It should support `?(RawThreadInfo | ThreadInfo | ServerThreadInfo)` as input
            - We should replace the `_find({ name: 'Admins' })` code in the codebase with this new function
            - We can use it on the client (in [D291](https://phabricator.ashoat.com/D291) instead of `memberIsAdmin`), and on the server side
    2. Condition 2: This only applies to threads where, besides the viewer, there is only one member, and that member has either blocked the viewer or is blocked by the viewer
        - If the thread has two members, that means it has both the viewer and the blocker/blockee
        - If the thread has only one member, that member is the blocker/blockee
    3. Condition 3: If the thread is a child thread, all of its ancestors must match condition 1 and 2
        - Enforcing this condition on the client will require recursively checking all of the ancestors threads in the `ThreadStore`
        - I made a new comment about this below since it will be pretty complicated
    4. The following permissions should be disabled: `VOICED`, `EDIT_ENTRIES`, `EDIT_THREAD`, `CREATE_SUBTHREADS`, `CREATE_SIDEBARS`, `JOIN_THREAD`, `EDIT_PERMISSIONS`, `ADD_MEMBERS`, `REMOVE_MEMBERS`
4. We should make sure the server follows the same restrictions as the client
    - Unlike the client, where we can enforce all of this in one place, the server might be a little harder. We will have to look at where each individual permission check occurs, and change how it's done
    - It might be possible to make this work by only changing one place: the `checkThreads` function. To do this though, we'll basically need to fetch all of the `memberships` rows. We could maybe call `fetchServerThreadInfos` from here (not `fetchThreadInfos` because it will filter the `members` list, see below). If we take this approach, we'll need to make sure that all of the checks go through `checkThreads`. I think most of them do, but I'm not sure all of them
    - Unlike on the client, where we will need to recursively check all ancestor threads to satisfy condition 3, we should be able to satisfy condition 3 by only checking the `memberships` rows for the child thread. This is because in the database, if you are a member of a parent thread but not a child thread, you should have a `role=0` `memberships` row for the child thread. The client doesn't see this because it gets [filtered](https://github.com/Ashoat/squadcal/blob/f120d2a19d44d56d05d1d2733109757d8bda7544/lib/shared/thread-utils.js#L138-L141) from the `RawThreadInfo.members` array before it's returned to the client
        - To satisfy that all ancestors match condition 1, we can check if anybody has the `CHANGE_ROLE` permission. This is the same hack we use in the link above. (It probably would be good to factor this out in a separate function)
        - To satisfy that all ancestors match condition 2, we can just check the number of entries in the `ServerThreadInfo.members` array

**Comment by Ashoat** [comment]
Regarding "Condition 3" on the client, ie. the recursive ancestor thread check. Right now there's no way to check this on the client without recursively checking all of the ancestor threads. This is because `role=0` `memberships` rows get [filtered](https://github.com/Ashoat/squadcal/blob/f120d2a19d44d56d05d1d2733109757d8bda7544/lib/shared/thread-utils.js#L138-L141) out on the server.

There are two ways I can think of for us to address condition 3 on the client:

1. Have `threadInfoFromRawThreadInfo` take multiple `RawThreadInfo`s
    - For the callsite in `threadInfoSelector`, we already have access to the full `threadStore`, and can pass it in. however, this will make performance a little worse, since it will mean that whenever one `ThreadInfo` changes, we will recreate every `ThreadInfo`
    - For the callsite in `sendPushNotifs`, we only need the `RawThreadInfo` so we can compose a notif message. we can probably just continue passing in a single `RawThreadInfo`, and make it so `threadInfoFromRawThreadInfo` doesn't crash in this case, and just avoids modifying the permissions blob if it isn't passed the parent
2. Make it so the client `RawThreadInfo` includes an entry for each `memberships` row. basically, we would get rid of this filtering logic: https://github.com/Ashoat/squadcal/blob/f120d2a19d44d56d05d1d2733109757d8bda7544/lib/shared/thread-utils.js#L138-L141
    - We would have to move that filter logic to some places on the client, like `ThreadSettings`, so we don't show these users in the list of members
     - We would need to write a script that would send `updateTypes.UPDATE_THREAD` updates to every user for any thread in their `ThreadStore` that is affected
    - These changes would not apply to older clients. we could either choose to ignore old clients and let them show non-members in `ThreadSettings`, or do something fancy where:
        - Old clients would continue getting `RawThreadInfo`s with a filtered member list
        - As soon as a client reports that is has upgraded to the newer version, we will start giving it the `RawThreadInfo` with the full member list, and will run the "script" to generate `updateTypes.UPDATE_THREAD` updates for them

I'm leaning towards #2... #1 feels too hacky. I don't like the idea of `threadInfoFromRawThreadInfo` silently ignoring the permissions check if it doesn't get passed parent `RawThreadInfo`s...

**Comment by Ashoat** [comment]
I followed up with @KatPo today a bit about this line in the previous comment:

> We could either choose to ignore old clients and let them show non-members in `ThreadSettings`, or do something fancy

We decided to "do something fancy" :)

There are three parts we need to do here:

1. Instead of running a script and generating updates for all of a user's clients, we now want to generate the updates for a specific client only when it upgrades. `createUpdates` supports sending an update to a specific session, but only for certain updates.
    - An example of an update that supports targeting session already is `updatesTypes.UPDATE_ENTRY`. In that case, we need to support updating specific sessions because not all clients have the same view into the calendar. If one client scrolls up on the calendar to see old calendar entries, and one of those calendar entries changes on the server, we only need to update the client that has scrolled up, and not the other clients.
    - We'll need to make `updateTypes.UPDATE_THREAD` support something similar. To do that we will add an optional `targetSession` property to `ThreadUpdateData`. We don't need to change `ThreadRawUpdateInfo` or `ThreadUpdateInfo` though, since these objects are only used once the target has been identified.
    - After adding the optional `targetSession` property, we only need to make a small change to `createUpdates` to look at this property. If we have a `targetSession`, we just need to set the `target` variable, similar to [how it's done](https://github.com/Ashoat/squadcal/blob/master/server/src/creators/update-creator.js#L268) for `UPDATE_ENTRY.
2. Once `updateTypes.UPDATE_THREAD` supports `targetSession`, we need to make sure the server generates the `updateTypes.UPDATE_THREAD` for a client whenever that client upgrades.
    - We can do this from `setCookiePlatformDetails`, which gets called whenever a client boots up and initializes a socket.
    - We can compare `viewer.platformDetails` to `platformDetails` to identify if the client `codeVersion` has changed.
    - If the client has upgraded to version 70 (next version), we will call `createUpdates`. To avoid having to deal with the updates ourselves, we can just not provide a `ViewerInfo` object to `createUpdates`. That will make it so the updates get put it in the `updates` table in the database, and they will be fetched right away when `fetchUpdateInfos` is called.
3. Finally, we will need to make sure that we continue providing the old `RawThreadInfo`s (with the member list filtered) to old clients, but we provide the new `RawThreadInfo`s to newer clients.
    - You've already started on this work in [D339](https://phabricator.ashoat.com/D339). We'll just need to make sure we continue filtering the member list for older clients.
    - There is a bit of complexity here because `rawThreadInfoFromServerThreadInfo` does not currently take a `codeVersion` parameter. It's called in two places:
        1. `rawThreadInfosFromServerThreadInfos` in `thread-fetchers.js`
            - This is the code we intend to change. We can look at `codeVersion` here.
        2. `sendPushNotifs`
            - Right now this code has access to each client's `codeVersion` through `PushInfo`, but it is generating just one set of `RawThreadInfo`s for each user, regardless of the client's `codeVersion`.
            - We could make it generate different `RawThreadInfo`s depending on the `codeVersion`, but actually I think this isn't really necessary. The `RawThreadInfo`s are just used to generate notif text, which should be okay either way.
    - Given that context, I think we can just modify `rawThreadInfoFromServerThreadInfo` to have a new parameter `filterMemberList?: boolean = true`. We will leave it unspecified at the `sendPushNotifs` callsite (so it defaults to `true`), but in `rawThreadInfosFromServerThreadInfos` we will set it depending on `viewer.platformDetails?.codeVersion`.

**Comment by KatPo** [comment]
Regarding checking permissions and blocked threads on server:
> It might be possible to make this work by only changing one place: the checkThreads function

Most of the checks are done in `checkThreads`, but `EDIT_ENTRIES` is also in `checkThreadPermissionForEntry`

Additionally, we need to make sure we are not showing delete and edit button when there are no permissions to edit entry

**Comment by Ashoat** [comment]
> Additionally, we need to make sure we are not showing delete and edit button when there are no permissions to edit entry

Thanks for noticing this today. Here's what I think we'll want to do:
1. Put a `threadHasPermission` check in `Calendar.makeActive`
2. In the main `Button` in `Entry`, put a `threadHasPermission` check and set it to `disabled` if there is no permission

> Most of the checks are done in `checkThreads`, but `EDIT_ENTRIES` is also in `checkThreadPermissionForEntry`

Thanks for finding all these callsites! @palys-swm recently set up `checkThreads` and we tried to make sure most of the checks go through there. Great to see that work paying off.

I ran `cd server && git grep threadPermissions` to try and make sure you didn't miss any callsites. I think there are two that you missed: the code in `createThread`/`updateThread` that checks `CREATE_SUBTHREADS`/`CREATE_SIDEBARS` on the parent thread. We look directly at the `RawThreadInfo` there, which unlike `ThreadInfo` isn't covered by [D291](https://phabricator.ashoat.com/D291). And since it doesn't go through `checkThreads` or any of the associated functions in `thread-permission-fetchers.js`, so it isn't covered by [D308](https://phabricator.ashoat.com/D308).

Some thoughts:
1. To address `createThread`/`updateThread`, I think we can try to make sure `RawThreadInfo` is "corrected" in the same way you correct `ThreadInfo` in [D291](https://phabricator.ashoat.com/D291).
    - Normally when we change something about `RawThreadInfo`, we need to think about how to update all the existing client `threadStore`s. But in this case, I grepped through the client code and found that all of the `threadHasPermission` checks go through `ThreadInfo` and not `RawThreadInfo`, with the exception of one in `message-reducer.js` that only checks `VISIBLE`. Since we already have the code in [D291](https://phabricator.ashoat.com/D291) to handle `ThreadInfo`, we should be okay.
    - I also doubt that anybody has blocked anybody else in prod, so we probably don'tt need to fix any `threadStore`s anyway. And if anything *is* wrong (even though it won't matter for the reasons described in the last bullet point), the `STATE_CHECK` mechanism should detect the inconsistency in the `threadStore` and correct it.
    - In terms of fixing up `RawThreadInfo`, I think we can do this in `rawThreadInfoFromServerThreadInfo`. We can use the same `threadIsWithBlockedUserOnly` function that you introduced in [D291](https://phabricator.ashoat.com/D291).
2. In the future, I'd love it if you could catch these callsites yourself. I want you to be able to operate more independently, without me having to check your work as much as I do now. I understand it can be hard to confirm which of these callsites matter or don't, so you shouldn't feel like you need to do it alone – you can always check with me if there's a part that's confusing. But my hope is that you can "own" this process going forward, and I can help you with the details, instead of me having to own the process.
3. I noticed some other places where we check permissions without checking block status:
    - There are many places in the codebase where we check permissions directly in SQL. This probably isn't ideal, but since we only use it to check `VISIBLE` and `KNOW_OF`, and since those aren't affected by block status, we should be okay. But let's keep this in mind in the future: most permissions can't just be checked directly in the database, since we need to check block status too.
    - In noticed in `deleteThread` we call `fetchThreadPermissionsBlob`, which bypasses `checkThreads` and so isn't covered by [D308](https://phabricator.ashoat.com/D308). I think it's fine to leave this for now since `DELETE_THREAD` isn't a permission that we're looking at. But I'd like to add a comment to the top of `fetchThreadPermissionsBlob` to clarify that it doesn't consider block status. Something like:

> Note that it's risky to verify permissions by inspecting the blob directly. There are other factors that can override permissions in the permissions blob, such as when one user blocks another. It's always better to go through `checkThreads` and friends, or by looking at the RawThreadInfo/ThreadInfo through threadHasPermission.

**Comment by Ashoat** [comment]
@KatPo pointed out today that my proposed approach for fixing the checks in `createThread`/`updateThread`, which is to make all `RawThreadInfo`s have the correct permission blob by changing `rawThreadInfoFromServerThreadInfo`, would require that `rawThreadInfoFromServerThreadInfo` gets passed `UserInfo`s with block status. To do that we would need to call `fetchKnownUserInfos` in `fetchThreadInfos`, which would be a bit wasteful since we call it elsewhere as well.

Given this context, I think it would be better to take a simpler solution:

1. For handling `createThread`/`updateThread`, we can just add a new fetch there. We can call `checkThreadPermission` on the parent thread ID, which goes through `checkThreads`, which is addressed in [D308](https://phabricator.ashoat.com/D308).
2. Separately, I'm a little concerned about somebody in the future calling `threadHasPermission` on a `RawThreadInfo` for a permission in `disabledWhenBlocked`. In a separate diff, I think we should update `threadHasPermission` so that if it gets passed a permission in `disabledWhenBlocked` and a `RawThreadInfo` (not a `ThreadInfo`), it will throw an error. We can achieve this with an `invariant` check. For checking `RawThreadInfo` vs. `ThreadInfo`, we can check if a `uiName` property exists.

**Comment by Ashoat** [comment]
All of this work is done! Congrats @KatPo :)
