### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [Ashoat/squadcal#120]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by Ashoat** [comment]
Thanks @pwntester!

- I've created a ["security policy"](https://github.com/Ashoat/squadcal/blob/master/SECURITY.md) that lists my email address
- I've created a ["draft security advisory"](https://github.com/Ashoat/squadcal/security/advisories/GHSA-f4mp-6x8r-h82m) and added you to it
