### ISSUE TITLE
"Chatting to yourself?" alert is displayed only once

### ISSUE THREAD

**Issue by zrebcu411** [Ashoat/squadcal#91]
I'm not sure if this is intended.

Steps to reproduce:

1. Click "compose thread" button
2. Do not select any users, just click `Create` button
3. `Chatting to yourself?` alert will be displayed. Click `Cancel` button to hide it.
4. Click `Create` button again
5. `Chatting to yourself?` alert is not displaying anymore

**Comment by Ashoat** [comment]
Oops. This was a dumb mistake on my part. Fixed in 5c9ea135d9836eabb4cb6f4373c1fe544c2e88b3
